# Generated by Django 3.1.4 on 2020-12-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201227_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop',
        ),
    ]
