# Generated by Django 3.1.4 on 2021-01-07 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_remove_news_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessCont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, unique=True, verbose_name='Тема сообщения')),
                ('plain_message', models.TextField(verbose_name='Текст сообщения')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Почта отправителя')),
                ('to', models.EmailField(max_length=254, verbose_name='Почта получателя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
